Flow type components
catalogueglobal/datatools-ui pull request #235
Opened 2018-08-21 17:02 UTC by landonreed

Add flow typing to library (nearly) all components.  Notable components this avoids are some of the modal components, which need to be refactored altogether because they rely heavily on refs and accept state/props through their `open` method, and the Settings components, which should see a refactor in #41.

2018-08-21 21:10 UTC, evansiroky commented on lib/alerts/components/AffectedServices.js
> +class ServicesHeader extends Component<{entities: Array<any>}> {
Should this be Array<AlertEntity> instead?  Seems like that would then negate the need for typing within each filter function.

2018-08-21 23:40 UTC, evansiroky commented on lib/common/components/MapModal.js
> +  // _onCreate (e) {
If we still need this even with comments, please indicate why and perhaps create a github issue.

2018-08-21 23:44 UTC, evansiroky commented on lib/common/user/Auth0Manager.js
> +        console.log(profile)
remove

2018-08-21 23:46 UTC, evansiroky commented on lib/editor/actions/active.js
> +      console.log('updating url', url, pathname)
remove

2018-08-21 23:58 UTC, evansiroky commented on lib/editor/components/EntityListSecondaryActions.js
> +  }: any) => {
elaborate a bit on this type

2018-08-22 00:02 UTC, evansiroky commented on lib/editor/components/FareRuleSelections.js
> +  _onContainsChange = (input: any) => {
Please elaborate a bit on the types of these change functions

2018-08-22 00:06 UTC, evansiroky commented on lib/editor/components/GtfsEditor.js
> +  setActivePatternSegment: () => void,
let's alphabetize these.  Try using [this plugin](https://atom.io/packages/sorter).

2018-08-22 00:15 UTC, evansiroky commented on lib/editor/components/map/EditorMap.js
> +  zoomToTarget: ?number,
Please alphabetize this.

2018-08-22 00:16 UTC, evansiroky commented on lib/editor/components/map/EditorMap.js
> +    // if (activeComponent === 'stop') {
Please add a comment explaining why this code is being kept.

2018-08-22 00:18 UTC, evansiroky commented on lib/editor/components/map/EditorMap.js
> +                activePattern={this.props.activePattern}
Please destructure out all these props.

2018-08-22 02:57 UTC, evansiroky commented on lib/editor/components/pattern/TripPatternViewer.js
> +          activePatternTripCount={this.props.activePatternTripCount}
Please destructure

2018-08-22 02:58 UTC, evansiroky commented on lib/editor/components/timetable/EditableCell.js
> +  renderTime: boolean,
Please alphabetize

2018-08-22 02:59 UTC, evansiroky commented on lib/editor/components/timetable/Timetable.js
> +  columns: Array<TimetableColumn>,
Alphabetize

2018-08-22 03:00 UTC, evansiroky commented on lib/editor/components/timetable/TimetableEditor.js
> +  setActiveCell: ?string => void,
Alphabetize

2018-08-22 03:02 UTC, evansiroky commented on lib/editor/components/timetable/TimetableGrid.js
> +  _renderLeftHeaderCell = ({ columnIndex, key, rowIndex, style }: { columnIndex: number, key: string, rowIndex: number, style: Style}) => (
Let's unwrap these to be more readable

2018-08-22 03:03 UTC, evansiroky commented on lib/editor/components/timetable/TimetableHeader.js
> +  addNewRow: (?boolean, ?boolean) => void,
Alphabetize

2018-08-22 03:10 UTC, evansiroky commented on lib/gtfsplus/components/GtfsPlusTable.js
> +  pageCount: number,
Alphabetize

2018-08-22 03:12 UTC, evansiroky commented on lib/manager/components/FeedSourceTable.js
> +  active: boolean,
Alphabetize

2018-08-22 03:34 UTC, evansiroky requested changes
Lots of great work here.  I think we should enable this eslint rule: https://github.com/gajus/eslint-plugin-flowtype#eslint-plugin-flowtype-rules-sort-keys  That way we can quickly alphabetize all these type definitions.

2018-08-23 16:55 UTC, landonreed commented on lib/editor/components/map/EditorMap.js
> +    // if (activeComponent === 'stop') {
I will remove the code entirely.  The click to select stop functionality was essentially completely hidden from users and not entirely reliable or necessary.

2018-08-23 18:07 UTC, landonreed commented
OK, @evansiroky.  I've addressed all of your comments.  Good to merge?

2018-08-28 16:20 UTC, evansiroky approved these changes
Great work and let's keep up the trend of keeping the e2e tests passing!

2018-08-28 16:41 UTC, merged