Create project and feed tweaks
catalogueglobal/datatools-ui pull request #255
Opened 2018-11-15 16:05 UTC by landonreed

A few tweaks for #41:

- auto focus first field in form
- use `validator` (which is already used in editor)
- add keydown listener for `ENTER` (to trigger save)
- show loading spinner after save to prevent form from emptying and looking like something went wrong

2018-11-20 06:08 UTC, evansiroky requested changes
There ought to be a validation check after pressing enter and before saving a feed source or project.  It'd probably be good to recalculate the form validation when enter is pressed and if everything looks good, continue with saving.

2018-11-20 06:08 UTC, evansiroky commented on lib/manager/components/CreateFeedSource.js
> +        this._onSave()
There needs to be some kind of validation check done before calling `_onSave`.  It's possible to create a feed source without a name with this change.

2018-11-20 06:08 UTC, evansiroky commented on lib/manager/components/ProjectSettingsForm.js
> +        this._onSaveSettings()
There needs to be some kind of validation check done before calling `_onSaveSettings`.  It's possible to create a project without a name with this change.

2018-11-28 15:40 UTC, landonreed commented
OK, @evansiroky, I made some changes that address the onSave issue. Let me know how it looks.

2018-11-30 23:43 UTC, evansiroky approved these changes

2018-12-03 21:45 UTC, merged