fix(trip-validation): prevent trip update http requests if trip data …
catalogueglobal/datatools-ui pull request #257
Opened 2018-11-16 16:35 UTC by landonreed

- [ ] prevents saving trips if invalid
- [ ] fixes #167 (invalid frequencies)
- [ ] adds list of trip validation issues to UI

2018-12-04 21:41 UTC, evansiroky commented on lib/editor/selectors/timetable.js
> +const isCellValueInvalid = (
This could use a unit test.

2018-12-04 21:41 UTC, evansiroky commented on lib/editor/selectors/timetable.js
> +export const getTripValidationErrors = createSelector(
This could use a unit test.

2018-12-04 21:42 UTC, evansiroky commented
Since we've now fixed the frequency editor in the timetable, we should add the basic e2e CRUD tests to make sure frequency editing keeps working.

2018-12-04 21:44 UTC, evansiroky requested changes
Needs to be mergeable to dev.  I think this is a good opportunity to also add unit and e2e tests, but that can be done later if merging this in is a priority.

2018-12-13 20:17 UTC, landonreed commented
@evansiroky, I'd like to close out everything ASAP in the catalogue repo so I prefer to merge now, but I'll create a ticket targeting this selector/util function for unit tests.

2018-12-14 22:33 UTC, evansiroky approved these changes
Allowing a merge without tests, so we can migrate to Conveyal repo.

2018-12-17 15:59 UTC, merged