Refactor flow typing in containers and use correct action types throughout application
catalogueglobal/datatools-ui pull request #271
Opened 2018-12-05 00:49 UTC by evansiroky

Seeks to resolve #265, #246, #183.

2018-12-14 06:19 UTC, evansiroky commented
Ready for review!

2018-12-17 21:41 UTC, landonreed requested changes
Looks really good, @evansiroky! Just a few comments and one big issue spotted in `AlertEditor`.  Also, can you fix the conflicts while you're at it?

2018-12-17 21:41 UTC, landonreed commented on lib/editor/components/timetable/TimetableEditor.js
> +  // this was GtfsRoute, but was changed to any based on the way it's derived from ActiveGtfsEditor
@evansiroky, this comment is confusing. It looks like it applies to `saveTripsForCalendar`, but I don't think it is intended to?

2018-12-17 21:41 UTC, landonreed commented on lib/admin/components/UserRow.js
> +import {deleteUser} from '../actions/admin'
Should this be a `*` import?

2018-12-17 21:41 UTC, landonreed commented on lib/alerts/actions/alerts.js
> +export function onAlertEditorMount (
I've noticed the use of a function to encapsulate the `componentWillMount` logic (as you do here), but also the placement of this logic directly inserted into `componentWillMount` (e.g., `UserAdmin`). Are there differences in these cases that warrant different approaches?

2018-12-17 21:41 UTC, landonreed commented on lib/alerts/components/AlertEditor.js
> +    const {alert, location, onAlertEditorMount, permissionFilter, user} = this.props
See above comment

2018-12-17 21:41 UTC, landonreed commented on lib/alerts/components/AlertEditor.js
> +  _deleteAlert = () => this.props.deleteActiveEntity(this.props.alert)
WARNING!!!! I think you used the wrong function here! I think this should be `this.props.deleteAlert`. `deleteActiveEntity` removes a stop, route (for example) from the active alert.

2018-12-17 21:41 UTC, landonreed commented on lib/alerts/components/AlertEditor.js
> +  _onRouteClick = (stop: GtfsRoute, agency: any, newEntityId: ?number) => {
Not a huge deal, but this `stop` arg should be renamed to `route`.

2018-12-17 21:41 UTC, landonreed commented on lib/common/components/SidebarNavItem.js
> +import type {Props as ConatinerProps} from '../containers/ActiveSidebarNavItem'
Misspelling "ContainerProps"

2018-12-17 21:41 UTC, landonreed commented on lib/common/components/StatusModal.js
> +  // put in here to make general destructuring just work
I don't entirely understand this comment. Where does this help out destructuring? Maybe it's just confusing because I'm viewing an excerpt of this file on GitHub, but the comment may need some more detail.

2018-12-17 21:41 UTC, landonreed commented on lib/common/containers/App.js
> -      },
Nice catch.

2018-12-17 21:41 UTC, landonreed commented on lib/editor/components/EditorHelpModal.js
> +    this.props.refreshEditor()
Yea, this is more intuitive. Nice one.

2018-12-17 21:41 UTC, landonreed commented on lib/editor/components/EntityListButtons.js
> +    }
Maybe a console.warn is warranted here?

2018-12-17 21:41 UTC, landonreed commented on lib/editor/components/EntityListButtons.js
> +          }
Console.warn might be good here also.

2018-12-17 21:41 UTC, landonreed commented on lib/editor/components/pattern/PatternStopCard.js
> +  // property is available through react dnd?
Correct.

2018-12-17 21:41 UTC, landonreed commented on lib/gtfsplus/components/GtfsPlusField.js
>      // tableId, rowIndex, fieldName, newValue
We can probably remove this comment.

2018-12-17 21:41 UTC, landonreed commented on lib/manager/containers/ActiveFeedSourceViewer.js
> +import type {} from '../../types'
What does importing these empty curly braces mean?

2018-12-17 21:41 UTC, landonreed commented on lib/manager/actions/projects.js
> +  (payload: $Shape<Project> & { organizationId: string }) => payload
Is an organizationId always required? I thought this was optional, but maybe I'm mistaken.

2018-12-17 21:41 UTC, landonreed commented on lib/public/components/PublicFeedSourceViewer.js
> +    // $FlowFixMe FIXME does this variable still exist in the feedSource type?
I think it is actually called `feedVersions`, which is the list of versions is added to its parent feed source object in the projects reducer under `RECEIVE_FEEDVERSIONS`. Perhaps we could handle this better, but yea `FeedSource#versions` doesn't appear to be a thing.

2018-12-18 00:00 UTC, evansiroky commented on lib/editor/components/timetable/TimetableEditor.js
> +  // this was GtfsRoute, but was changed to any based on the way it's derived from ActiveGtfsEditor
Looks like the comment isn't even needed now anyways.

2018-12-18 00:01 UTC, evansiroky commented on lib/alerts/actions/alerts.js
> +export function onAlertEditorMount (
Not really, sorry for the inconsitencies.  I actually prefer to put the logic into the component's componentWillMount method.  Shall we try to adhere to that pattern?

2018-12-18 00:05 UTC, evansiroky commented on lib/alerts/components/AlertEditor.js
> +  _deleteAlert = () => this.props.deleteActiveEntity(this.props.alert)
Good catch, will fix.

2018-12-18 00:09 UTC, evansiroky commented on lib/alerts/components/AlertEditor.js
> +  _deleteAlert = () => this.props.deleteActiveEntity(this.props.alert)
Creating https://github.com/conveyal/datatools-ui/issues/387 so that we can catch stuff like this in the future.

2018-12-18 00:22 UTC, evansiroky commented on lib/common/components/StatusModal.js
> +  // put in here to make general destructuring just work
I think it's in reference to the stuff going on in line 97 of this file.  I guess it seemed weird for an action to be a state variable, so I made a comment.

2018-12-18 00:23 UTC, evansiroky commented on lib/editor/components/EntityListButtons.js
> +    }
ok

2018-12-18 00:23 UTC, evansiroky commented on lib/editor/components/EntityListButtons.js
> +          }
ok

2018-12-18 00:23 UTC, evansiroky commented on lib/gtfsplus/components/GtfsPlusField.js
>      // tableId, rowIndex, fieldName, newValue
ok

2018-12-18 00:24 UTC, evansiroky commented on lib/manager/containers/ActiveFeedSourceViewer.js
> +import type {} from '../../types'
It probably means I initially was importing types, but then deleted all the imports but not this line altogether.

2018-12-18 00:26 UTC, evansiroky commented on lib/manager/actions/projects.js
> +  (payload: $Shape<Project> & { organizationId: string }) => payload
oh interesting, it is not required in datatools-server.  I'll remove this typing.

2018-12-18 00:27 UTC, evansiroky commented on lib/public/components/PublicFeedSourceViewer.js
> +    // $FlowFixMe FIXME does this variable still exist in the feedSource type?
ah, I see.

2018-12-18 01:28 UTC, evansiroky commented
All items should be resolved except for https://github.com/catalogueglobal/datatools-ui/pull/271#discussion_r242363037 for which I await your feedback, @landonreed.

2018-12-18 20:40 UTC, landonreed commented on lib/alerts/actions/alerts.js
> +export function onAlertEditorMount (
No worries. It doesn't really add much obfuscation and I'm kind of indifferent. Let's just leave it where it is for now.

2018-12-18 20:42 UTC, landonreed approved these changes
LGTM, thanks @evansiroky!

2018-12-18 20:43 UTC, merged